### ISSUE TITLE
? auth0 redirection is not available on /oauth/token endpoint

### ISSUE THREAD

**Issue by nowherenearithaca** [auth0/rules#121]
The sms-mfa example is slick, and I seemed to have gotten implemented for use as part of a non-hosted login scenario.  However, when it tries to do the redirect to the webtask, auth0 errors out with the error "auth0 redirection is not available on /oauth/token endpoint".

Is there a config somewhere that needs to be set as well for this to work in that case?

**Comment by AmaanC** [comment]
The `/oauth/token` endpoint in your situation is being used for the [password grant](https://auth0.com/docs/api-auth/grant/password), which can't support redirects since authentication is done through an XHR request.

We [list all the flows and when to use them here](https://auth0.com/docs/api-auth/which-oauth-flow-to-use). How this translates to auth0.js or Lock depends, but here's a fairly generic example for auth0.js combined with [Hosted Login Pages](https://auth0.com/docs/hosted-pages/login):

```
webAuth.authorize({
  audience: 'https://mystore.com/api/v2',
  scope: 'read:order write:order',
  // 'code' for authZ code grant (server side confidential clients)
  // Change to 'token' or 'token id_token' for implicit grant (SPAs)
  responseType: 'code',
  redirectUri: 'https://example.com/auth/callback'
});
```

Using it that way, the flow looks like this:

- example.com/login
- yourtenant.auth0.com/authorize?response_type=code&...
- Redirect to your SMS MFA configuration for when the Rule applies
- yourtenant.auth0.com/continue?state=redirect-state
- yourtenant.auth0.com/login/callback - processes and redirects to redirect_uri
- example.com/auth/callback

Hope that makes sense!

[Auth0.js v8 is documented here](https://auth0.com/docs/libraries/auth0js/v8).
[Lock v10 is documented here](https://auth0.com/docs/libraries/lock/v10).
