### ISSUE TITLE
Yubico-MFA doesn't receive OTP code

### ISSUE THREAD

**Issue by danclarke** [auth0/rules#139]
When the user provides the OTP code the form is correctly submitted with the otp code, however it doesn't appear in either the context or req parameters. This means 'undefined' is passed through to the Yubico validation servers and the auth fails.

I can't find any way of getting the otp value other than sending it through as a GET parameter instead.

**Comment by InetJustin** [comment]
This is correct, I was able to find [#4889 ](https://github.com/auth0/docs/issues/4889) where [santiagoaguiar](https://github.com/santiagoaguiar) got this working 6 months ago. The input elements in that sample form aren't actually made part of the context.data object because of some settings. He illustrates how to fix this (and it does work). They merged his one change but not this one I guess.

**Comment by joshcanhelp** [comment]
Apologies for the long delay ... examples here are being reviewed for accuracy and security now.
