### ISSUE TITLE
What are the contexts in which I can use rules

### ISSUE THREAD

**Issue by adriatic** [auth0/rules#17]
The very definition `Rules are code snippets written in JavaScript that are executed as part of the authentication pipeline in Auth0` makes rules one of the most powerful feature in Auth0 platform. However, the statement `Create authorization rules based on complex logic (anything that can be written with node.js).` written on the page at <https://auth0.com/docs/rules> indicates that one can use rules only of the app is hosted on node.js.

I think that **Auth0 should be completely platform agnostic** so I would like to know how can I use rules in an angular app hosted by ASP.NET

**Comment by dschenkelman** [comment]
Hi @adriatic,

You don't need to write your application in node.js to be able to take advantage of rules. Rules are executed whenever a user logs in to an application/client.

All you need to do to use rules is to go to the **Rules** tab in your dashboard and create rules with your logic. The _"anything that can be written with node.js"_ part is there because you write your rules using node.js, not because you need to be using node.js as your app's server component.

**Comment by jfromaniello** [comment]
I think there is an issue with that part of the documentation, because it is not node.

Node.js is the underlying technology powering our sandbox, but you write rules in javascript. It is not **anything that can be written with node.js** it is restricted to what we allow in the sandbox.

**Comment by mgonto** [comment]
I'll reopen this issue to add a note to clarify this :).

**Comment by adriatic** [comment]
After seeing the comment from @dschenkelman I was about warn that `because you write your rules using node.js,` is likely a typo, and the word `node.js` should be replaced with `javascript` only to find that @jfromaniello already addressed that. Thanks :-)

**Comment by adriatic** [comment]
I also have a question on the `sandbox`: does this mean that I cannot use rules outside of this `sandbox`? If the sandbox is provided for practicing the rules, I do not really need it as I can practice in my own context and then also use it in my context.
